//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliverySerialization.cl_UserAuthentication", Namespace="http://schemas.datacontract.org/2004/07/ILogisticWebAPI")]
    public partial class DeliverySerializationcl_UserAuthentication : object
    {
        
        private string userauthenticationdataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userauthenticationdata
        {
            get
            {
                return this.userauthenticationdataField;
            }
            set
            {
                this.userauthenticationdataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliverySerialization.cl_GrnNotification", Namespace="http://schemas.datacontract.org/2004/07/ILogisticWebAPI")]
    public partial class DeliverySerializationcl_GrnNotification : object
    {
        
        private string grnnotificationdataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string grnnotificationdata
        {
            get
            {
                return this.grnnotificationdataField;
            }
            set
            {
                this.grnnotificationdataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliverySerialization.cl_OrderNotification", Namespace="http://schemas.datacontract.org/2004/07/ILogisticWebAPI")]
    public partial class DeliverySerializationcl_OrderNotification : object
    {
        
        private string ordernotificationdataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ordernotificationdata
        {
            get
            {
                return this.ordernotificationdataField;
            }
            set
            {
                this.ordernotificationdataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDeliveryDetails")]
    public interface IDeliveryDetails
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryDetails/getUserAuthenticate", ReplyAction="http://tempuri.org/IDeliveryDetails/getUserAuthenticateResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> getUserAuthenticateAsync(ServiceReference1.DeliverySerializationcl_UserAuthentication requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryDetails/getGrnNotification", ReplyAction="http://tempuri.org/IDeliveryDetails/getGrnNotificationResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> getGrnNotificationAsync(ServiceReference1.DeliverySerializationcl_GrnNotification requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryDetails/getOrderNotification", ReplyAction="http://tempuri.org/IDeliveryDetails/getOrderNotificationResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> getOrderNotificationAsync(ServiceReference1.DeliverySerializationcl_OrderNotification requestData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IDeliveryDetailsChannel : ServiceReference1.IDeliveryDetails, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DeliveryDetailsClient : System.ServiceModel.ClientBase<ServiceReference1.IDeliveryDetails>, ServiceReference1.IDeliveryDetails
    {
        
        public DeliveryDetailsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> getUserAuthenticateAsync(ServiceReference1.DeliverySerializationcl_UserAuthentication requestData)
        {
            return base.Channel.getUserAuthenticateAsync(requestData);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> getGrnNotificationAsync(ServiceReference1.DeliverySerializationcl_GrnNotification requestData)
        {
            return base.Channel.getGrnNotificationAsync(requestData);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> getOrderNotificationAsync(ServiceReference1.DeliverySerializationcl_OrderNotification requestData)
        {
            return base.Channel.getOrderNotificationAsync(requestData);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
